/// Flutter icons QuoteIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  QuoteIcons
///      fonts:
///       - asset: fonts/QuoteIcons.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class QuoteIcons {
  QuoteIcons._();

  static const _kFontFam = 'QuoteIcons';

  static const IconData quote_left = const IconData(0xf10d, fontFamily: _kFontFam);
  static const IconData quote_right = const IconData(0xf10e, fontFamily: _kFontFam);
}
